/*
 * LinTrcv.h
 *
 *  Created on: Mar 19, 2019
 *      Author: messam
 */

#ifndef STUBS_LINTRCV_H_
#define STUBS_LINTRCV_H_

enum class LinTrcv_TrcvModeType {LINTRCV_TRCV_MODE_NORMAL, LINTRCV_TRCV_MODE_STANDBY, LINTRCV_TRCV_MODE_SLEEP};
enum class LinTrcv_TrcvWakeupReasonType {LINTRCV_WU_ERROR, LINTRCV_WU_NOT_SUPPORTED, LINTRCV_WU_BY_BUS, LINTRCV_WU_BY_PIN,
	LINTRCV_WU_INTERNALLY, LINTRCV_WU_RESET, LINTRCV_WU_POWER_ON};
enum class LinTrcv_TrcvWakeupModeType {LINTRCV_WUMODE_ENABLE, LINTRCV_WUMODE_DISABLE, LINTRCV_WUMODE_CLEAR};

#endif /* STUBS_LINTRCV_H_ */
